language: node_js
node_js:
- node
branches:
  only:
  - master
  - /^greenkeeper-.*$/
  - /^greenkeeper/.*$/
cache: npm
notifications:
  email:
    on_success: always
    on_failure: always
before_script:
- npm i -g @angular/cli
- greenkeeper-lockfile-update
script:
- ng build --prod --progress=false
after_script:
  - greenkeeper-lockfile-upload
before_install:
- npm i -g greenkeeper-lockfile
# we do extract the deploy_rsa in Travis /tmp folder to avoid deploying the decrypted key by any mean.
- openssl aes-256-cbc -K $encrypted_1cf7eed8785d_key -iv $encrypted_1cf7eed8785d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts:
  - eldero.beget.tech
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/dist/ eldero_travis@eldero.beget.tech:./
  on:
    branch: master
